#include "stdbool.h"
#include "stdio.h"

#include "uti.h"

bool pack_resource_c_file(const char* path, size_t index, char* data, size_t data_size) {
    char c_path[512];
    snprintf(c_path, 512 - 1, "%s/data_%zu.c", path, index + 1);
    {
        FILE *out = fopen(c_path, "wb");
        if (out == NULL) {
            sprintf("ERROR: could not open file %s for writing\n", c_path);
            return false;
        }

        fprintf(out, "// Do not modify this file, it is generated by resource_packer.c");
        fprintf(out, "// data_%zu.c - Generated by resource_packer.c\n", index + 1);
        fprintf(out, "// It has (%zu) bytes of data\n", data_size);
        fprintf(out, "#include \"resource_accessor.h\"\n\n");
        fprintf(out, "unsigned char data_%zu[] = {\n", index + 1);

        // data inserted here
        size_t row_size = 20;
        for (size_t i = 0; i < data_size; ){
            //fprintf(out, "    ");
            for (size_t col = 0; col < row_size && i < data_size; ++col, ++i) {
                fprintf(out, "0x%02X,", (unsigned char)data[i]);
            }
            fprintf(out, "\n");
        }
        fprintf(out, "};\n");

        printf("INFO: Sucessfully built data file (%s)\n", c_path);

        fclose(out);
    }
    return true;
}

bool pack_resource_accessor_header(const char* path) {
    char filename[512];
    snprintf(filename, 512 - 1, "%s/resource_accessor.h", path);
    FILE *out = fopen(filename, "wb");
    if (out == NULL) {
        sprintf("ERROR: could not open file %s for writing\n", filename);
        return false;
    }

    fprintf(out, "// Do not modify this file, it is generated by resource_packer.c\n");
    fprintf(out, "#ifndef RESOURCE_ACCESSOR_H_\n");
    fprintf(out, "#define RESOURCE_ACCESSOR_H_\n");
    fprintf(out, "#include <stdbool.h>\n");
    fprintf(out, "#include <stddef.h>\n");
    fprintf(out, "bool ra_access_resource_by_file_path(const char *file_path, char **data, size_t *out_size);\n");
    fprintf(out, "#endif // RESOURCE_ACCESSOR_H_\n");

    printf("INFO: Sucessfully built header file (%s)\n", filename);

    fclose(out);

    return true;
}

bool pack_resource_accessor_c_file(const char* path, size_t* size_array, char** filename_array, size_t length) {
    char filename[512];
    snprintf(filename, 512 - 1, "%s/resource_accessor.c", path);
    FILE *out = fopen(filename, "wb");
    if (out == NULL) {
        sprintf("ERROR: could not open file %s for writing\n", filename);
        return false;
    }

    fprintf(out, "// Do not modify this file, it is generated by resource_packer.c\n");
    fprintf(out, "#include \"resource_accessor.h\"\n");
    fprintf(out, "#include \"stdio.h\"\n");
    fprintf(out, "#include \"stdbool.h\"\n");
    fprintf(out, "#include \"string.h\"\n");
    fprintf(out, "\n");
    fprintf(out,"typedef struct {\n");
    fprintf(out,"    const char *file_path;\n");
    fprintf(out,"    const size_t size;\n");
    fprintf(out,"    unsigned char *data;\n");
    fprintf(out,"} Ra_Info;\n");
    fprintf(out, "\n");
    for(size_t i = 0; i < length; i++) {
        fprintf(out,"extern unsigned char data_%zu[];\n", i + 1);
    }
    fprintf(out, "\n");
    fprintf(out,"#define RA_RESOURCES_LENGTH %zu\n", length);
    fprintf(out,"Ra_Info ra_resources_table[RA_RESOURCES_LENGTH] = {\n");
    for(size_t i = 0; i < length; i++) {
        fprintf(out,"    {\"%s\", %zu, data_%zu},\n", filename_array[i], size_array[i], i + 1);
    }
    fprintf(out,"};\n");
    fprintf(out, "\n");
    fprintf(out,"bool ra_access_resource_by_file_path(const char *file_path, char **data, size_t *out_size) {\n");
    fprintf(out,"    for(size_t i = 0; i < RA_RESOURCES_LENGTH; i++) {\n");
    fprintf(out,"        if (strcmp(ra_resources_table[i].file_path, file_path) == 0 ) {\n");
    fprintf(out,"            *data = (char*)ra_resources_table[i].data;\n");
    fprintf(out,"            *out_size = ra_resources_table[i].size;\n");
    fprintf(out,"            return true;\n");
    fprintf(out,"        }\n");
    fprintf(out,"    }\n");
    fprintf(out,"    printf(\"WARNING: could not find resource %%s in recource_accessor.\\n\", file_path);\n");
    fprintf(out,"    return false;\n");
    fprintf(out,"}\n");
    fprintf(out, "\n");
    fclose(out);

    printf("INFO: Sucessfully built c_file file (%s)\n", filename);

    return true;
}


int main(int argc, char** argv) {

    // argv[1] is packed_resource_out_path
    // argv[2:] are the resource file names
    if (argc < 2) {
        printf("ERROR: no resources defined in Makefile. %s:%d\n", __FILE__, __LINE__);
        return 234;
    }

    char* packed_resource_out_path = argv[1];
    size_t count = argc - 2;
    char** start = argv + 2;

#define RA_MAX_FILES 2048
    size_t sizes[RA_MAX_FILES];

    for (size_t i = 0; i < count; i++) {
        char* content;
        size_t size;
        uti_read_entire_file(start[i], &content, &size);
        pack_resource_c_file(packed_resource_out_path, i, content, size);
        sizes[i] = size;
    }

    pack_resource_accessor_header(packed_resource_out_path);
    pack_resource_accessor_c_file(packed_resource_out_path, sizes, start, count);

    return 0;
}